{% set name = "deadline" %}
{% set version = "10.4.0.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://thinkbox-installers.s3.us-west-2.amazonaws.com/Releases/Deadline/10.4/1_{{version}}/Deadline-{{version}}-linux-installers.tar # [linux64]
  sha256: 4bfd8ea08985af18b4650e06110702bf43d1e7be7b3e9217013567ba65f8d0b6 # [linux64]
  #sha256: 4abfececa88d8f24ce2edeca9201f396598ae37626351eb6c3356e273b841598 # [linux64]
  patches:
   - 0001-Fix-script-path.patch

build:
  number: 0
  # These build options for repackaging an application
  # https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
  - "**"

test:
  commands:
    - deadlinecommand --help
    - deadlinecommandbg --help

about:
  summary: Deadline 10 job runtime used to run legacy Deadline 10 jobs in AWS Deadline Cloud
  dev_url: https://aws.amazon.com/thinkbox-deadline/
  license: Thinkbox-EULA
  license_file:
    - ThinkboxEULA.txt
